const page=await figma.getNodeByIdAsync('584:2961');await figma.setCurrentPageAsync(page);
for(const s of['Regular','Medium','SemiBold'])await figma.loadFontAsync({family:'Geist',style:s});await figma.loadFontAsync({family:'Geist Mono',style:'Regular'});
const col=(await figma.variables.getLocalVariableCollectionsAsync()).find(c=>c.name==='Quire');const V={};for(const id of col.variableIds){const v=await figma.variables.getVariableByIdAsync(id);V[v.name]=v;}
const AL={bg:'bg/page',side:'bg/sidebar',s:'bg/surface',s2:'bg/surface-2',s3:'bg/surface-3',sunk:'bg/sunken',b:'border/default',bs:'border/strong',dv:'border/divider',t:'text/primary',t2:'text/secondary',t3:'text/tertiary',inv:'text/inverse',a:'accent/base',on:'accent/on',as:'accent/soft',green:'semantic/green',gs:'semantic/green-soft',amber:'semantic/amber',ams:'semantic/amber-soft',red:'semantic/red',rs:'semantic/red-soft',violet:'label/violet',blue:'label/blue',teal:'label/teal',rose:'label/rose',orange:'label/orange'};
const hx=h=>({r:parseInt(h.slice(1,3),16)/255,g:parseInt(h.slice(3,5),16)/255,b:parseInt(h.slice(5,7),16)/255});
const P=(n,op)=>{let p;if(n[0]==='#')p={type:'SOLID',color:hx(n)};else p=figma.variables.setBoundVariableForPaint({type:'SOLID',color:{r:0,g:0,b:0}},'color',V[AL[n]||n]);if(op!=null)p={...p,opacity:op};return p;};
const COMP={};for(const c of page.findAllWithCriteria({types:['COMPONENT']}))COMP[c.name]=c;
const pad=(f,p)=>{if(p==null)return;const a=Array.isArray(p)?p:[p,p,p,p];if(a.length===2){a.push(a[0],a[1]);}f.paddingTop=a[0];f.paddingRight=a[1];f.paddingBottom=a[2];f.paddingLeft=a[3];};
function F(par,o={}){const f=figma.createAutoLayout(o.dir==='v'?'VERTICAL':'HORIZONTAL');f.name=o.name||'Frame';f.fills=o.fill?[P(o.fill,o.fop)]:[];if(o.gap!=null)f.itemSpacing=o.gap;pad(f,o.pad);if(o.ai)f.counterAxisAlignItems=o.ai;else if(o.dir!=='v')f.counterAxisAlignItems='CENTER';if(o.jc)f.primaryAxisAlignItems=o.jc;if(o.r)f.cornerRadius=o.r;if(o.wrap){f.layoutWrap='WRAP';f.counterAxisSpacing=o.wrap;}
if(o.st){f.strokes=[P(o.st)];f.strokeAlign='INSIDE';if(o.sides){f.strokeTopWeight=o.sides.includes('t')?1:0;f.strokeBottomWeight=o.sides.includes('b')?1:0;f.strokeLeftWeight=o.sides.includes('l')?1:0;f.strokeRightWeight=o.sides.includes('r')?1:0;}else f.strokeWeight=o.sw||1;}
if(o.clip)f.clipsContent=true;if(o.shadow)f.effects=[{type:'DROP_SHADOW',color:{r:.1,g:.09,b:.08,a:o.shadow},offset:{x:0,y:12},radius:32,spread:-8,visible:true,blendMode:'NORMAL'}];
if(par)par.appendChild(f);if(par&&o.abs){f.layoutPositioning='ABSOLUTE';}
if(typeof o.w==='number'){f.resize(o.w,f.height);if(par&&!o.abs)f.layoutSizingHorizontal='FIXED';else f[o.dir==='v'?'counterAxisSizingMode':'primaryAxisSizingMode']='FIXED';}else if(o.w==='fill')f.layoutSizingHorizontal='FILL';
if(typeof o.h==='number'){f.resize(f.width,o.h);if(par&&!o.abs)f.layoutSizingVertical='FIXED';else f[o.dir==='v'?'primaryAxisSizingMode':'counterAxisSizingMode']='FIXED';}else if(o.h==='fill')f.layoutSizingVertical='FILL';
if(o.abs){f.x=o.x||0;f.y=o.y||0;}if(o.op!=null)f.opacity=o.op;return f;}
function X(par,s,o={}){const t=figma.createText();t.fontName={family:o.mono?'Geist Mono':'Geist',style:o.mono?'Regular':(o.wt||'Regular')};t.characters=String(s);t.fontSize=o.size||13;t.fills=[P(o.c||'t')];if(o.lh)t.lineHeight={unit:'PIXELS',value:o.lh};if(o.ls!=null)t.letterSpacing={unit:'PERCENT',value:o.ls};if(o.upper)t.textCase='UPPER';if(o.strike)t.textDecoration='STRIKETHROUGH';if(o.center)t.textAlignHorizontal='CENTER';par.appendChild(t);if(o.w==='fill'){t.textAutoResize='HEIGHT';t.layoutSizingHorizontal='FILL';}else if(typeof o.w==='number'){t.resize(o.w,t.height);t.textAutoResize='HEIGHT';}if(o.trunc){t.textAutoResize='NONE';t.textTruncation='ENDING';t.maxLines=1;t.resize(typeof o.w==='number'?o.w:t.width,t.height);if(o.w==='fill')t.layoutSizingHorizontal='FILL';}return t;}
function I(par,n,sz=16,c){const i=COMP['icon/'+n].createInstance();par.appendChild(i);if(sz!==16)i.resize(sz,sz);if(c)for(const x of i.findAll(k=>'strokes' in k&&k.strokes.length))x.strokes=[P(c)];return i;}
function G(par,n){const i=COMP[n].createInstance();par.appendChild(i);return i;}
const M={am:['AM','#5A67D8'],sc:['SC','#C54B78'],jc:['JC','#3B82C4'],ew:['EW','#23918A'],pp:['PP','#C48A1E'],ml:['ML','#8662C9'],lf:['LF','#3D8E5F'],da:['DA','#C0612B']};
const NM={am:'Alex Morgan',sc:'Sarah Chen',jc:'John Carter',ew:'Emma Wilson',pp:'Priya Patel',ml:'Marcus Lee',lf:'Lena Fischer',da:'Diego Alvarez'};
function AV(par,k,sz=20){const f=F(par,{name:'avatar/'+(k||'none'),w:sz,h:sz,r:sz/2,jc:'CENTER',fill:k?M[k][1]:null,fop:.18,st:k?null:'bs'});if(k)X(f,M[k][0],{size:Math.round(sz*.4),wt:'SemiBold',c:M[k][1]});else I(f,'user',Math.round(sz*.55),'t3');return f;}
function AVS(par,ks,sz=20){const f=F(par,{name:'avatars',gap:-5});ks.forEach(k=>{const a=AV(f,k,sz);a.strokes=[P('s')];a.strokeWeight=1.5;a.strokeAlign='OUTSIDE';});return f;}
function BTN(par,label,o={}){const k=o.k||'secondary';const f=F(par,{name:'button/'+k,h:o.sm?26:o.lg?36:30,pad:[0,o.sm?8:11],gap:6,r:6,jc:'CENTER',fill:k==='primary'?'a':k==='secondary'?'s':k==='danger'?'red':null,st:k==='secondary'?'bs':null,w:o.w});if(o.icon)I(f,o.icon,14,k==='primary'?'on':k==='danger'?'#FFFFFF':k==='ghost'?'t2':'t');if(label)X(f,label,{size:o.sm?11.5:o.lg?13.5:12.5,wt:'Medium',c:k==='primary'?'on':k==='danger'?'#FFFFFF':k==='ghost'?'t2':'t'});return f;}
function IB(par,n,o={}){const f=F(par,{name:'icon-button',w:o.sz||28,h:o.sz||28,r:6,jc:'CENTER',fill:o.on?'s3':null});I(f,n,o.i||16,o.c||'t2');return f;}
function BADGE(par,label,o={}){const c=o.c||'t2';const f=F(par,{name:'badge',h:20,pad:[0,7],gap:5,r:5,fill:o.bg||'s2',st:o.bg?null:'b'});if(o.dot){const d=F(f,{w:6,h:6,r:3,fill:c});}if(o.icon)I(f,o.icon,11,c);X(f,label,{size:11.5,wt:'Medium',c});return f;}
const LBC={Design:'violet',Frontend:'blue',Backend:'teal',Research:'amber',Content:'rose',Bug:'red',QA:'green',Growth:'orange'};
function LBL(par,n){const f=F(par,{name:'label/'+n,h:20,pad:[0,7,0,6],gap:5,r:5,st:'b',fill:'s'});F(f,{w:6,h:6,r:2,fill:LBC[n]});X(f,n,{size:11.5,c:'t2'});return f;}
const STN={backlog:'Backlog',todo:'To Do',progress:'In Progress',review:'Review',done:'Done'};const PRN={urgent:'Urgent',high:'High',medium:'Medium',low:'Low',none:'No priority'};
function STP(par,s,o={}){const f=F(par,{name:'status-pill',gap:6,pad:o.pad});G(f,'status/'+s);X(f,STN[s],{size:o.size||12.5});return f;}
function PRP(par,p,o={}){const f=F(par,{name:'priority-pill',gap:6});G(f,'priority/'+p);X(f,PRN[p],{size:o.size||12.5,c:p==='none'?'t3':'t'});return f;}
function KBD(par,k){const f=F(par,{name:'kbd',h:18,pad:[0,5],r:4,st:'b',fill:'s',jc:'CENTER'});X(f,k,{mono:true,size:10.5,c:'t2'});return f;}
function PROG(par,v,w=120,c='a'){const f=F(par,{name:'progress',w,h:4,r:2,fill:'s3',clip:true});const i=F(f,{w:Math.max(1,w*v/100),h:4,r:2,fill:c});return f;}
function INPUT(par,o={}){const f=F(par,{name:'input',h:o.h||30,pad:[0,10],gap:8,r:6,st:o.err?'red':o.focus?'a':'bs',fill:'s',w:o.w||'fill'});if(o.icon)I(f,o.icon,14,'t3');X(f,o.v||o.ph||'',{size:o.size||13,c:o.v?'t':'t3'});if(o.kbd){F(f,{w:'fill'});}if(o.kbd)KBD(f,o.kbd);if(o.focus){f.effects=[{type:'DROP_SHADOW',color:{r:.29,g:.36,b:.84,a:.15},offset:{x:0,y:0},radius:0,spread:3,visible:true,blendMode:'NORMAL'}];}return f;}
function FIELD(par,label,o={}){const f=F(par,{name:'field',dir:'v',gap:6,w:o.w||'fill'});X(f,label,{size:12.5,wt:'Medium'});INPUT(f,o);if(o.err){const e=F(f,{gap:4});I(e,'circle-alert',12,'red');X(e,o.err,{size:11.5,c:'red'});}else if(o.hint)X(f,o.hint,{size:11.5,c:'t3'});return f;}
const PC={indigo:'#5A67D8',blue:'#3B82C4',violet:'#8662C9',teal:'#23918A',rose:'#C54B78',amber:'#C48A1E',green:'#3D8E5F'};
function PICO(par,icon,c,sz=28){const f=F(par,{name:'project-icon',w:sz,h:sz,r:sz>30?9:7,jc:'CENTER',fill:PC[c],fop:.14});I(f,icon,Math.round(sz*.55),PC[c]);return f;}
function PDOT(par,c,sz=8){return F(par,{name:'dot',w:sz,h:sz,r:3,fill:PC[c]||c});}
function SP(par){return F(par,{name:'spacer',w:'fill',h:1});}
async function SECTION(name,y){let s=page.findChild(n=>n.type==='SECTION'&&n.name===name);if(!s){s=figma.createSection();s.name=name;s.x=0;s.y=y;s.fills=[{type:'SOLID',color:{r:.96,g:.957,b:.945}}];}return s;}
function SCREEN(sec,name,i,o={}){const w=o.w||1440,h=o.h||900;const f=figma.createFrame();f.name=name;f.resize(w,h);f.fills=[P(o.fill||'s')];f.clipsContent=true;sec.appendChild(f);const gap=o.gap||120;f.x=120+i*(w+gap);f.y=200;return f;}
function FIT(sec){let mx=0,my=0;for(const c of sec.children){mx=Math.max(mx,c.x+c.width);my=Math.max(my,c.y+c.height);}sec.resizeWithoutConstraints(mx+120,my+120);}
function LABEL(sec,title,sub){let t=sec.findChild(n=>n.name==='Section title');if(t)return;const f=figma.createFrame();f.name='Section title';f.fills=[];sec.appendChild(f);f.layoutMode='VERTICAL';f.itemSpacing=8;f.primaryAxisSizingMode='AUTO';f.counterAxisSizingMode='AUTO';f.x=120;f.y=64;const a=figma.createText();a.fontName={family:'Geist',style:'SemiBold'};a.characters=title;a.fontSize=40;a.fills=[{type:'SOLID',color:hx('#1D1C1A')}];a.letterSpacing={unit:'PERCENT',value:-2};f.appendChild(a);if(sub){const b=figma.createText();b.fontName={family:'Geist',style:'Regular'};b.characters=sub;b.fontSize=18;b.fills=[{type:'SOLID',color:hx('#64615B')}];f.appendChild(b);}}
function TOP(main,crumbs,o={}){const t=F(main,{name:'Topbar',h:46,w:'fill',pad:[0,12,0,14],gap:6,st:'b',sides:'b',fill:'s'});const cr=F(t,{name:'Breadcrumbs',gap:6});const ws=F(cr,{w:16,h:16,r:4,fill:'#2F2E2A',jc:'CENTER'});X(ws,'N',{size:9,wt:'SemiBold',c:'#FFFFFF'});['Northwind Studio',...crumbs].forEach((c,i,a)=>{X(cr,c,{size:12.5,c:i===a.length-1?'t':'t2',wt:i===a.length-1?'Medium':'Regular'});if(i<a.length-1)X(cr,'/',{size:11,c:'t3'});});SP(t);if(o.extra)o.extra(t);const s=F(t,{name:'Search',h:26,w:220,pad:[0,6,0,9],gap:8,r:6,st:'b',fill:'sunk'});I(s,'search',14,'t3');X(s,'Search or jump to…',{size:12.5,c:'t3'});SP(s);KBD(s,'⌘K');IB(t,'bell');BTN(t,'New task',{k:'primary',sm:true,icon:'plus'});AV(t,'am',26);return t;}
function SHELL(sec,name,i,active,crumbs,o={}){const f=SCREEN(sec,name,i);f.layoutMode='HORIZONTAL';f.primaryAxisSizingMode='FIXED';f.counterAxisSizingMode='FIXED';f.counterAxisAlignItems='MIN';const sb=COMP['Sidebar'].createInstance();f.appendChild(sb);sb.layoutSizingVertical='FILL';if(active){const it=sb.findOne(n=>n.name==='nav/'+active);if(it){it.fills=[P('s')];it.strokes=[P('b')];it.strokeWeight=1;const tx=it.findOne(n=>n.type==='TEXT');if(tx){tx.fontName={family:'Geist',style:'Medium'};tx.fills=[P('t')];}}}
const main=F(f,{name:'Main',dir:'v',w:'fill',h:'fill',fill:'s'});TOP(main,crumbs,o);const content=F(main,{name:'Content',dir:'v',w:'fill',h:'fill',clip:true,pad:o.flush?0:[28,32,32,32],gap:o.flush?0:20,fill:'s'});return {f,main,content};}
function PH(par,title,sub,acts){const h=F(par,{name:'Page header',w:'fill',ai:'MIN',gap:12});const l=F(h,{dir:'v',gap:4,w:'fill'});X(l,title,{size:23,wt:'SemiBold',ls:-2.2});if(sub)X(l,sub,{size:13.5,c:'t2'});if(acts){const a=F(h,{gap:6});acts(a);}return h;}
function PANEL(par,title,o={}){const p=F(par,{name:'Panel/'+title,dir:'v',w:o.w||'fill',r:10,st:'b',fill:'s',clip:true});if(title){const h=F(p,{name:'Panel header',w:'fill',pad:[12,14,10,14],gap:8});X(h,title,{size:13.5,wt:'SemiBold'});if(o.acts){SP(h);o.acts(h);}}return p;}
