// Emits src/00-icons.js: only the Lucide icons the app actually references.
// Every quoted kebab-case token in the sources is checked against Lucide; matches are inlined.
const fs = require('fs'), path = require('path');
const L = require('./lucide-0.460.0.min.js'); const I = L.icons || L;
const src = path.join(__dirname, '..', 'src');
const text = fs.readdirSync(src).filter(f => /\.(js|html)$/.test(f) && f !== '00-icons.js').map(f => fs.readFileSync(path.join(src, f), 'utf8')).join('\n');
const pascal = n => n.split('-').map(p => p[0].toUpperCase() + p.slice(1)).join('');
const names = [...new Set([...text.matchAll(/['"`]([a-z][a-z0-9]*(?:-[a-z0-9]+)*)['"`]/g)].map(m => m[1]))].filter(n => I[pascal(n)]).sort();
const out = {};
for (const n of names) {
  let node = I[pascal(n)]; if (node[0] === 'svg') node = node[2];
  out[n] = node.map(([t, a]) => `<${t} ${Object.entries(a).filter(([k]) => k !== 'key').map(([k, v]) => `${k}="${v}"`).join(' ')}/>`).join('');
}
process.stdout.write(`/* Generated by tools/gen-icons.js from Lucide 0.460.0 (ISC). ${names.length} icons. Do not edit. */\nconst ICONS = ${JSON.stringify(out)};\n`);
